name: Lint
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/cache@v5
        with:
          path: node_modules
          key: ${{ runner.os }}/node-18/${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}/node-18/
      - run: npm install
      - run: npm run lint
