name: Release
on:
  release:
    types: [published]
permissions:
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: v1/${{ runner.os }}/node-20/${{ hashFiles('**/package.json') }}
          restore-keys: v1/${{ runner.os }}/node-20/
      - run: npm install
        env:
          PERCY_POSTINSTALL_BROWSER: true
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
